### PR TITLE
Reduce duplication in stylix

### LINKED ISSUE #234: Duplication in `stylix/{darwin,hm,nixos}`
Particularly `palette.nix`, which is identical under `darwin` and `nixos`, and very similar for `hm`.

### PR DESCRIPTION
**Pull request by dwarfmaster**
Fix dudplication in `stylix/*/fonts.nix` and `stylix/*/palette.nix`.

I haven't tested on macos, so if someone could test it there that would be great.

Fixes #234

### CODE REVIEW

**Review by jalil-salame — APPROVED** [review]
Looks good to me. It also looks easy to adapt #201 to support this c:

**Comment by dwarfmaster** [comment]
Maybe we can wait for #201 to be merged, and I'll update this PR at that point.

**Comment by jalil-salame** [comment]
> Maybe we can wait for #201 to be merged, and I'll update this PR at that point.

This looks easier to review and merge than my PR.

**Review by danth — APPROVED** [review]
Looks good.

IMO we should merge this now and update #201 to support it.

**Comment by jalil-salame** [comment]
> Looks good.
> 
> IMO we should merge this now and update #201 to support it.

Updated #201 with support for this

**Pull request merged**
