### PR TITLE
lock: updating helix-base16 input

### LINKED ISSUE #467: [Feature request] Bump flake / update base16-helix
base16 repo has updated its base16 theme following [this issue](https://github.com/tinted-theming/base16-helix/issues/13) with [this PR](https://github.com/tinted-theming/base16-helix/pull/15)

### PR DESCRIPTION
**Pull request by Ciflire**
fix #467

### CODE REVIEW

**Review by trueNAHO — COMMENTED** [review]
LGTM.

Do you also want to include the latest commits: https://github.com/tinted-theming/base16-helix/compare/687ace01e99566bd48e984363da7185ddae913b2..HEAD ? If so, you can just do it in this PR to declutter the commit history.

**Comment by Ciflire** [comment]
force push to squash commits
should be all good now

**Review by trueNAHO — APPROVED** [review]
LGTM.

Is it alright for you if I declare @LennyPenny as co-author, as this PR supersedes the nearly identical https://github.com/danth/stylix/pull/466 PR?

**Comment by Ciflire** [comment]
ofc

**Pull request merged**
