### PR TITLE
bemenu: Move over to HM's module

### PR DESCRIPTION
**Pull request by Noodlez1232**
HM just added a new bemenu module upstream, so this commit changes the stylix bemenu module to use that instead.

### CODE REVIEW

**Comment by Noodlez1232** [comment]
A little confused as to why the build is failing.

**Comment by danth** [comment]
It's building against an older version of Home Manager. If you run `nix flake update` and commit the new lock file, it should succeed

**Comment by Noodlez1232** [comment]
Went ahead and updated the flake.lock file, and it should be good now.

**Comment by Noodlez1232** [comment]
It looks good to me that new change. Is there anything I need to do on my end?

**Comment by danth** [comment]
This was supposed to automatically merge once the tests finished; I'm not sure why that never happened.

**Comment by Noodlez1232** [comment]
It *should* be ready now! Sorry for the late response.

**Review by danth — APPROVED** [review]

**Comment by danth** [comment]
> This was supposed to automatically merge once the tests finished; I'm not sure why that never happened.

I forgot to click approve, so the requirements to merge were never met :sweat_smile:

**Pull request merged**
