### PR TITLE
doc: add GitHub star history

### PR DESCRIPTION
**Pull request by trueNAHO**
Add the GitHub star history to illustrate the project's popularity and enhance its chances of wider adoption.

Reference:

- https://github.com/trueNAHO/dotfiles/commit/44fbb604ca88238091c1989614808b600cb412dd

Here is what the illustration looks like:

<picture>
  <source
    media="(prefers-color-scheme: dark)"
    srcset="https://api.star-history.com/svg?repos=danth/stylix&amp;type=Date&amp;theme=dark"
  />

  <source
    media="(prefers-color-scheme: light)"
    srcset="https://api.star-history.com/svg?repos=danth/stylix&amp;type=Date"
  />

  Star History Chart
</picture>

### CODE REVIEW

**Review by danth — COMMENTED** [review]
Note that this also appears in the documentation, where the color scheme doesn't perfectly match.

image

Is there a transparent version of the image (possibly from another service) which we can use?

**Comment by trueNAHO** [comment]
> this also appears in the documentation, where the color scheme doesn't perfectly match.

The default background color seems to be [`#0d1117`](https://github.com/star-history/star-history/pull/366/files#diff-3c71ae4ddac372038f62dc69ce05abc151966365578eb869491260e96252bcffR113).

> Is there a transparent version of the image (possibly from another service) which we can use?

Apparently, [such an option exists](https://github.com/star-history/star-history/pull/366), but I cannot figure out how to use.

**Comment by pyrox0** [comment]
So, I know this isn't my project, and far be it from me to say how a project should advertise itself, but why? What use does this serve? How does it "enhance its chances of wider adoption", as you say? This doesn't seem to be useful. Yes, large projects use it, but correlation does not equal causation. If anything, I would say that star history graphs are used by large projects to show that they are popular, but don't help when a project is small(not that I think they help anyways)

**Comment by jalil-salame** [comment]
> > Is there a transparent version of the image (possibly from another service) which we can use?
> 
> Apparently, [such an option exists](https://github.com/star-history/star-history/pull/366), but I cannot figure out how to use.

Isn't it adding `&transparent=true` to the end of the URL.

Also, the URL looks weird:

```
// Upstream example
https://api.star-history.com/svg?repos=star-history/star-history&type=Date&theme=dark

// This PR
https://api.star-history.com/svg?repos=danth/stylix&amp;theme=dark

// Expected URL
https://api.star-history.com/svg?repos=danth/stylix&theme=dark&transparent=true
```

**Comment by danth** [comment]
> How does it "enhance its chances of wider adoption", as you say?

Presumably by showing the star count and how it has gradually increased over time, which demonstrates the longevity of the project.

Although they can be useful in some aspects, I would agree that a star chart could make it feel like the project exists for the primary purpose of gaining popularity, rather than providing code.

> Also, the URL looks weird

This is HTML embedded in a Markdown document. As described in [the HTML specification](https://www.w3.org/TR/REC-html40/charset.html#h-5.3.2):

> Authors should use `&amp;` (ASCII decimal 38) instead of `&` to avoid confusion with the beginning of a character reference (entity reference open delimiter). Authors should also use `&amp;` in attribute values since character references are allowed within CDATA attribute values.

**Comment by trueNAHO** [comment]
> So, I know this isn't my project, and far be it from me to say how a project should advertise itself, but why? What use does this serve? How does it "enhance its chances of wider adoption", as you say? This doesn't seem to be useful. Yes, large projects use it, but correlation does not equal causation. If anything, I would say that star history graphs are used by large projects to show that they are popular, but don't help when a project is small(not that I think they help anyways)

> > How does it "enhance its chances of wider adoption", as you say?
>
> Presumably by showing the star count and how it has gradually increased over time, which demonstrates the longevity of the project.
>
> Although they can be useful in some aspects, I would agree that a star chart could make it feel like the project exists for the primary purpose of gaining popularity, rather than providing code.

Thanks for all the insightful comments. Frankly, I had not considered these popularity advertisement implications.

Upon discovering this tool, I simply thought it is interesting to see that the popularity of most popular projects increases exponentially rather than linearly:

Star History Chart

This information might be more relevant in a pitch rather than the project itself. Feel free to close this PR.

**Comment by trueNAHO** [comment]
> > So, I know this isn't my project, and far be it from me to say how a project should advertise itself, but why? What use does this serve? How does it "enhance its chances of wider adoption", as you say? This doesn't seem to be useful. Yes, large projects use it, but correlation does not equal causation. If anything, I would say that star history graphs are used by large projects to show that they are popular, but don't help when a project is small(not that I think they help anyways)
>
> > > How does it "enhance its chances of wider adoption", as you say?
> >
> >
> > Presumably by showing the star count and how it has gradually increased over time, which demonstrates the longevity of the project.
> > Although they can be useful in some aspects, I would agree that a star chart could make it feel like the project exists for the primary purpose of gaining popularity, rather than providing code.
>
> Thanks for all the insightful comments. Frankly, I had not considered these popularity advertisement implications.

The ["Factors contributing to daily stars"](https://github.com/emanuelef/daily-stars-explorer/blob/7a1896f5f3e77bb2029d3a904ca9acdd926acc99/website/src/info.md#factors-contributing-to-daily-stars) section might be interesting.

**Comment by trueNAHO** [comment]
Closing this PR based on https://github.com/danth/stylix/pull/312#issuecomment-2074981439.

**Pull request closed without merging**
