### PR TITLE
gnome: moved gnome-shell overlay outside its gnome packages umbrella

### PR DESCRIPTION
**Pull request by dasj19**
Once with this PR https://github.com/NixOS/nixpkgs/pull/338583 got merged the gnome-shell overlay did not have any effect, moreover stylix flake stopped building on the latest master of nixpkgs.

This PR removed the outer gnome overlay and let the gnome-shell be modified as a standalone package.

Note: this is the first time I look at stylix codebase and I might have overlooked things. If you think of something missing please ping me.

Edit: The error I got when using the latest nixpkgs master branch:

```
error:
       … while calling the 'head' builtin

         at /nix/store/gi5jqh2i4djgqz45vljnpz0bhnxdafgv-source/lib/attrsets.nix:1575:11:

         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'value'

         at /nix/store/gi5jqh2i4djgqz45vljnpz0bhnxdafgv-source/lib/modules.nix:821:9:

          820|     in warnDeprecation opt //
          821|       { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          822|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attribute 'gnome-shell' missing

       at /nix/store/nbcyd1kbx2w64g4qniz4jmss6x19q2f1-modules/gnome/nixos.nix:26:23:

           25|       gnome = super.gnome.overrideScope (gnomeSelf: gnomeSuper: {
           26|         gnome-shell = gnomeSuper.gnome-shell.overrideAttrs (oldAttrs: {
             |                       ^
           27|           # Themes are usually applied via an extension, but extensions are
```

### CODE REVIEW

**Comment by trueNAHO** [comment]
> Once with this PR [NixOS/nixpkgs#338583](https://github.com/NixOS/nixpkgs/pull/338583) got merged the gnome-shell overlay did not have any effect, moreover stylix flake stopped building on the unstable.

Consider updating the Nixpkgs input in Stylix to that particular commit to ensure Stylix stays in sync.

**Comment by dasj19** [comment]
@trueNAHO I changed the following in my stylix fork:
```
- nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
+ nixpkgs.url = "github:NixOS/nixpkgs/ca9576c81da013b7ab7a302990f7928d33e85198";
```
Then did a `nixos-rebuild switch --flake .` As expected it builds on this branch but it does not on master.

**Comment by trueNAHO** [comment]
> I changed the following in my stylix fork:
>
> ```
> - nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
> + nixpkgs.url = "github:NixOS/nixpkgs/ca9576c81da013b7ab7a302990f7928d33e85198";
> ```
>
> Then did a `nixos-rebuild switch --flake .` As expected it builds on this branch but it does not on master.

Sorry for being unclear: Could you update your patch (this PR) to include the Nixpkgs update in the `flake.lock` file?

> I'm not sure what to commit here. when the next update of nixpkgs-unstable is going to happen this issue is going to affect stylix users.

I am not very familiar with the current GNOME setup. @danth, might be more helpful here.

**Comment by dasj19** [comment]
@trueNAHO I was trying to say that the issue https://github.com/NixOS/nixpkgs/pull/338583 was introduced today and https://github.com/NixOS/nixpkgs/tree/nixpkgs-unstable the changes in abovementioned PR did not reach `nixpkgs-unstable` yet. The latest commit in `nixpkgs-unstable` is from yesterday.

However when the changes land in the `nixpkgs-unstable` branch we will not be able to use stylix with gnome-shell.

So even if I bump the flake version of nixpkgs now it will not have any effect because the master branch of nixpkgs was not merged into `nixpkgs-unstable` yet.

I'll happily bump the nixpkgs in flake.lock after the mentioned changes lands in `nixpkgs-unstable`.

**Comment by dasj19** [comment]
Just updated flake.lock as the gnome-shell changes landed in `nixpkgs-unstable` branch

**Comment by trueNAHO** [comment]
> Edit: I'm going to need some help with the failing tests

I think we need to wait for https://github.com/NixOS/nixpkgs/pull/338836 to land.

Related: https://github.com/danth/stylix/issues/542

**Comment by danth** [comment]
> I think we need to wait for https://github.com/NixOS/nixpkgs/pull/338836 to land.

Since #544 is merged, rebasing this branch on `master` should fix the tests since none of them have Hyprland enabled.

**Review by danth — APPROVED** [review]
The GNOME testbed was built successfully, which proves this works with the new pinned version of Nixpkgs.

**Pull request merged**
