### PR TITLE
Add emacs hm module

### LINKED ISSUE #55: Request: Support for emacs (Home Manager module).
It would be nice to have emacs themed by stylix. This Issue is more or less a documentation for my manual theming, until I (or someone else) find some time to create a PR.

For reference, I'm using this code to supply a `base16-theme` (although I'm using the `emacs-init` module from rycee's NUR):
```nix
        base16-theme = {
          enable = true;
          config = ''
            (defvar base16-stylix-theme-colors
              '(:base00 "${config.lib.stylix.colors.withHashtag.base00}"
                :base01 "${config.lib.stylix.colors.withHashtag.base01}"
                :base02 "${config.lib.stylix.colors.withHashtag.base02}"
                :base03 "${config.lib.stylix.colors.withHashtag.base03}"
                :base04 "${config.lib.stylix.colors.withHashtag.base04}"
                :base05 "${config.lib.stylix.colors.withHashtag.base05}"
                :base06 "${config.lib.stylix.colors.withHashtag.base06}"
                :base07 "${config.lib.stylix.colors.withHashtag.base07}"
                :base08 "${config.lib.stylix.colors.withHashtag.base08}"
                :base09 "${config.lib.stylix.colors.withHashtag.base09}"
                :base0A "${config.lib.stylix.colors.withHashtag.base0A}"
                :base0B "${config.lib.stylix.colors.withHashtag.base0B}"
                :base0C "${config.lib.stylix.colors.withHashtag.base0C}"
                :base0D "${config.lib.stylix.colors.withHashtag.base0D}"
                :base0E "${config.lib.stylix.colors.withHashtag.base0E}"
                :base0F "${config.lib.stylix.colors.withHashtag.base0F}")
              "All colors for Base16 stylix are defined here.")

            ;; Define the theme
            (deftheme base16-stylix)

            ;; Add all the faces to the theme
            (base16-theme-define 'base16-stylix base16-stylix-theme-colors)

            ;; Mark the theme as provided
            (provide-theme 'base16-stylix)

            (load-theme 'base16-stylix t)
          '';
        };
```

I still need to think about how I can:

 - [x] Remove the dependency on `emacs-init` (probably using `extraConfig` from the HM module for emacs).
 - [x] Explicitly pull in the dependency for `pkgs.emacsPackages.base16-theme`

### PR DESCRIPTION
**Pull request by CRTified**
Closes #55.

Feedback is really appreciated, I'm not that experienced with elisp.

~~Line 48/49 sadly add more than intended to the `custom-theme-load-path` (the directory with the combined emacs packages), but that might be a minor issue, as it (AFAICT) only affects `custom-theme-load-path`, thus the theme engine, nothing else.~~

It works on my system (:tm:) when using my fork with this module.

### CODE REVIEW

**Comment by danth** [comment]
This looks reasonable in terms of the NixOS module and how it will combine with any existing configuration.

I don't use emacs so there's not much I can say about the lisp code. I'll merge this as-is soon unless anyone else leaves a review.

**Comment by CRTified** [comment]
I found a solution for the "big" impact of line 48/49. emacs provides [a method to resolve symlinks](https://www.gnu.org/software/emacs/manual/html_node/elisp/Truenames.html#index-file_002dtruename), making it easy to resolve the symlinks.`custom-theme-load-path` is now extended with the path to *only* the stylix theme package, nothing more.

**Comment by Gavinok** [comment]
Looks good to me as a lisper

**Review by Gavinok — APPROVED** [review]
Looks good to me as an occasional Elisper

**Review by danth — APPROVED** [review]

**Pull request merged**
