### PR TITLE
wofi: specify a unit (pt) for font size

### PR DESCRIPTION
**Pull request by jezcope**
Without a unit specified in wofi's `style.css`, it emits a warning and defaults to using pixels, which (on my screens anyway) results in the font being larger than intended. This explicitly sets the unit to `pt`.

### CODE REVIEW

**Comment by trueNAHO** [comment]
IIRC, rofi, tofi, and wofi are pretty much the same and might have the same API.

Can you verify whether https://github.com/danth/stylix/pull/552/commits/d31d392590d05caa4410fec37f728926782aeeb3 resolves the same issue in those applications? *NOTE: I did not test this.*

**Review by cgahr — APPROVED** [review]
This change fixes the issue with wofi (I did not try this commit, I added `pt` by hand).

**Review by cgahr — APPROVED** [review]

**Comment by cgahr** [comment]
> Can you verify whether [d31d392](https://github.com/danth/stylix/commit/d31d392590d05caa4410fec37f728926782aeeb3) resolves the same issue in those applications? _NOTE: I did not test this._

PS: the referenced commit is not the correct one

**Comment by jezcope** [comment]
Just tried `tofi` (love it, by the way, it's replaced wofi for me) and it **does not** want `pt` specified: it errors if you add that to the font size with `[ERROR]: Failed to parse "14pt" as unsigned int.`

I haven't used rofi for a while but skimming through its docs it looks like its syntax for styling fonts is slightly different and only needs the number. Example taken from rofi's own theming docs:

```css
* {
    background-color:      Black;
    text-color:            White;
    border-color:          White;
    font:            "Times New Roman 12";
}
```

So AFAICT there was no issue with stylix's configs for tofi and rofi, only for wofi.

**Review by trueNAHO — APPROVED** [review]
# Changelog

## v2: https://github.com/danth/stylix/pull/552/commits/205c3d2e215ee51bc0e74c8fc81b8204e180f732

- Do not specify font size unit as pt for `rofi`
- Do not specify font size unit as pt for `tofi`
- Simplify commit header
- `Link:` to related issue
- `Link:` to GitHub PR
- Add `Reviewed-by: NAHO <90870942+trueNAHO@users.noreply.github.com>` tag

## v1: https://github.com/danth/stylix/pull/552/commits/d31d392590d05caa4410fec37f728926782aeeb3

- Specify font size unit as pt for `rofi`
- Specify font size unit as pt for `tofi`

## v0: https://github.com/danth/stylix/pull/552/commits/c8d491255d763d24a82e1d39bc5e081a8d221fa7

**Comment by trueNAHO** [comment]
@cgahr, if you want we can add your `Tested-by` tag to the commit. If so, should we use the information from https://patch-diff.githubusercontent.com/raw/cgahr/latexplotlib/pull/38.patch?

**Comment by cgahr** [comment]
I'm not really sure what you are talking about. What does latexplotlib have to do with that?

**Comment by trueNAHO** [comment]
> I'm not really sure what you are talking about.

Just adding metadata to the commit that you successfully tested it.

> What does latexplotlib have to do with that?

I was referring to the whether the name and email should be the one from the `From: <NAME> <EMAIL>` line in the linked patch.

**Comment by cgahr** [comment]
Ah I see. Please use
26804763+cgahr@users.noreply.github.com
Thanks! (Also I just learned more about privacy with github)

**Comment by trueNAHO** [comment]
Should I use the name from the linked PR or just your GitHub account name?

**Comment by cgahr** [comment]
Github please

**Comment by trueNAHO** [comment]
I can also just not include your `Tested-by` tag, if you prefer. Sorry for bothering.

**Comment by cgahr** [comment]
Don't worry! Feel free to include it

**Review by danth — APPROVED** [review]
LGTM

**Pull request merged**
