### PR TITLE
stylix: bump tinted-kitty input

### PR DESCRIPTION
**Pull request by trueNAHO**
Closes: https://github.com/danth/stylix/issues/567
Link: https://github.com/danth/stylix/pull/588

### CODE REVIEW

**Comment by trueNAHO** [comment]
Cc: @psynyde

**Comment by trueNAHO** [comment]
@psynyde, can you confirm whether this PR resolves https://github.com/danth/stylix/issues/567.

**Comment by psynyde** [comment]
> @psynyde, can you confirm whether this PR resolves #567.

Yes, this should solve the issue.

**Review by danth — APPROVED** [review]
LGTM

**Comment by psynyde** [comment]
@trueNAHO sorry to bother you again, But updating stylix to latest commit is causing the same issue as #576 it seems like. I did some research and the issue is caused from [this commit](https://github.com/tinted-theming/tinted-kitty/commit/9569d8a3e8dad5714174a015d955642641d295fb#diff-46d429f4b19179f06d6ff725d2dc2c8d24914503d59c4ab5fb27a0330b2c445f) from tinted-kitty where they updated the `templates/config.yaml` file. the same this that causes the issue for tintet-foot.

**Pull request merged**
