### PR TITLE
hyprland: adapt breaking changes

### PR DESCRIPTION
**Pull request by diniamo**
https://github.com/hyprwm/Hyprland/commit/d1638a09bacd84b994de3f77746b74f427b9d41e

### CODE REVIEW

**Review by danth — APPROVED** [review]
Looks good to me

**Comment by tfkhdyt** [comment]
image

This PR causes an issue when using Hyprland from nixpkgs (unstable) which is still in version 0.44.1

**Comment by tfkhdyt** [comment]
> image
> 
> This PR causes an issue when using Hyprland from nixpkgs (unstable) which is still in version 0.44.1

image
My workaround is to lock the input flake to the previous commit

**Comment by diniamo** [comment]
Should have waited for a stable release with the commit before merging this. I forgot to mention that.

**Comment by trueNAHO** [comment]
> My workaround is to lock the input flake to the previous commit

Considering that it will take a while for the mentioned Hyprland commit to reach `nixpkgs/nixos-unstable`, I have reverted this PR in https://github.com/danth/stylix/pull/608.

**Comment by diniamo** [comment]
FWIW, there is a Hyprland release coming in a few days.

**Comment by trueNAHO** [comment]
> FWIW, there is a Hyprland release coming in a few days.

IIRC, Vaxry's Hyprland release schedule is not periodic, making it somewhat unreliable to wait on its next release.

Either way, https://github.com/danth/stylix/pull/608 has been merged.

**Comment by diniamo** [comment]
I know, he specifically said so in the Discord. I'm not making things up.

**Comment by DaRacci** [comment]
since some people (admittedly probably not too many) do follow the latest master commits maybe it would be worth having a staging branch for stylix that can apply fixes like these before they would appear in nixpkgs?

**Comment by diniamo** [comment]
You can always use my branch, I'll make a take 2 draft PR so it's easier to find.

**Comment by trueNAHO** [comment]
> since some people (admittedly probably not too many) do follow the latest master commits maybe it would be worth having a staging branch for stylix that can apply fixes like these before they would appear in nixpkgs?

Mixing `nixpkgs/nixos-unstable` and `hyprland/master` could be done by declaring a different `config` in `/modules/hyprland/hm.nix` depending on an added `inputs.hyprland` Stylix input, pointing to `hyprland/master`.

**Pull request merged**
