### PR TITLE
Tmux support

### PR DESCRIPTION
**Pull request by SomeGuyNamedMy**
tmux support using the base16 port

### CODE REVIEW

**Comment by SomeGuyNamedMy** [comment]
Ready to merge

**Comment by dwarfmaster** [comment]
LGTM. However there are a lot of commits that are not relevant to the PR, even though they cancel each other. It'd advise squashing them before merging.

**Comment by dwarfmaster** [comment]
I'd advise rebasing on master instead of merging, but otherwise don't worry too much about it. Squashing all commits of a PR can be done easily from the github interface when merging by the maintainer.

**Review by danth — APPROVED** [review]
Thanks!

**Pull request merged**
